### ISSUE TITLE
It's trying to start a boolean query?

### ISSUE THREAD

**Issue by RNCTX** [nextcloud/fulltextsearch_elasticsearch#30]
Nextcloud v13.0.2
fulltextsearch apps v0.7.2
elasticsearch server v6.2.4

output of index operation...

```
sudo -u www php /usr/local/www/nginx/nextcloud/occ fulltextsearch:index
indexing Files.
 USER: admin
- RAM: 6.8445739746094
 . Indexing: Documents
 . Indexing: Documents/About.odt
 . Indexing: Documents/About.txt
 . Indexing: Nextcloud Manual.pdf
 . Indexing: Nextcloud.mp4
 . Indexing: Photos
 . Indexing: Photos/Coast.jpg
 . Indexing: Photos/Hummingbird.jpg
 . Indexing: Photos/Nut.jpg
 USER: files
 . Indexing: Documents
 . Indexing: Documents/About.odt
 . Indexing: Documents/About.txt
 . Indexing: Nextcloud Manual.pdf
 . Indexing: Nextcloud.mp4
 . Indexing: Photos
 . Indexing: Photos/Coast.jpg
 . Indexing: Photos/Hummingbird.jpg
 . Indexing: Photos/Nut.jpg
 . Indexing: The Politics of Benjamin Franklins Satiric Personae 1722–1757.pdf
```
Output in elasticsearch log of failed search for the word _test_

```
[2018-05-29T15:26:22,104][DEBUG][o.e.a.s.TransportSearchAction] [node-1] [nextcloud][1], node[eROJng8pThy3uqGwmdmG7Q], [P], s[STARTED], a[id=qsmhX_7dTUev40zVEFjg0A]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[nextcloud], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[standard], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, source={"from":0,"size":10,"query":{"bool":{"must":[{"bool":{"should":[{"bool":{"should":[{"bool":{"should":[{"match_phrase_prefix":{"content":{"query":"test","slop":0,"max_expansions":50,"boost":1.0}}},{"match_phrase_prefix":{"title":{"query":"test","slop":0,"max_expansions":50,"boost":1.0}}},{"match_phrase_prefix":{"share_names.files":{"query":"test","slop":0,"max_expansions":50,"boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"filter":[{"bool":{"must":[{"term":{"provider":{"value":"files","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},{"bool":{"should":[{"term":{"owner":{"value":"files","boost":1.0}}},{"term":{"users":{"value":"files","boost":1.0}}},{"term":{"users":{"value":"__all","boost":1.0}}},{"term":{"groups":{"value":"admin","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},{"match_all":{"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"highlight":{"pre_tags":[""],"post_tags":[""],"fields":{"content":{}}}}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [node-1][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: failed to create query: {
  "bool" : {
    "must" : [
      {
        "bool" : {
          "should" : [
            {
              "bool" : {
                "should" : [
                  {
                    "bool" : {
                      "should" : [
                        {
                          "match_phrase_prefix" : {
                            "content" : {
                              "query" : "test",
                              "slop" : 0,
                              "max_expansions" : 50,
                              "boost" : 1.0
                            }
                          }
                        },
                        {
                          "match_phrase_prefix" : {
                            "title" : {
                              "query" : "test",
                              "slop" : 0,
                              "max_expansions" : 50,
                              "boost" : 1.0
                            }
                          }
                        },
                        {
                          "match_phrase_prefix" : {
                            "share_names.files" : {
                              "query" : "test",
                              "slop" : 0,
                              "max_expansions" : 50,
                              "boost" : 1.0
                            }
                          }
                        }
                      ],
                      "adjust_pure_negative" : true,
                      "boost" : 1.0
                    }
                  }
                ],
                "adjust_pure_negative" : true,
                "boost" : 1.0
              }
            }
          ],
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      }
    ],
    "filter" : [
      {
        "bool" : {
          "must" : [
            {
              "term" : {
                "provider" : {
                  "value" : "files",
                  "boost" : 1.0
                }
              }
            }
          ],
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      },
      {
        "bool" : {
          "should" : [
            {
              "term" : {
                "owner" : {
                  "value" : "files",
                  "boost" : 1.0
                }
              }
            },
            {
              "term" : {
                "users" : {
                  "value" : "files",
                  "boost" : 1.0
                }
              }
            },
            {
              "term" : {
                "users" : {
                  "value" : "__all",
                  "boost" : 1.0
                }
              }
            },
            {
              "term" : {
                "groups" : {
                  "value" : "admin",
                  "boost" : 1.0
                }
              }
            }
          ],
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      },
      {
        "match_all" : {
          "boost" : 1.0
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:320) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:707) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:558) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:534) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:330) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.4.jar:6.2.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalArgumentException: Can't parse boolean value [test], expected [true] or [false]
	at org.elasticsearch.index.mapper.BooleanFieldMapper$BooleanFieldType.indexedValueForSearch(BooleanFieldMapper.java:176) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.mapper.TermBasedFieldType.termQuery(TermBasedFieldType.java:54) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.mapper.BooleanFieldMapper$BooleanFieldType.termQuery(BooleanFieldMapper.java:124) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.search.MatchQuery.termQuery(MatchQuery.java:306) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.search.MatchQuery.blendTermQuery(MatchQuery.java:513) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:265) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.MatchPhrasePrefixQueryBuilder.doToQuery(MatchPhrasePrefixQueryBuilder.java:177) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:405) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:381) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:405) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:381) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:405) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:381) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:405) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:379) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:707) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:558) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:534) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:330) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.4.jar:6.2.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_162]
```

**Comment by RNCTX** [comment]
Nevermind, reset/re-index fixed it.  Very strange behavior from elasticsearch.

/shrug
