### ISSUE TITLE
NC 14: field [content] not present as part of path [attachment.content]

### ISSUE THREAD

**Issue by morph027** [nextcloud/fulltextsearch_elasticsearch#36]
## `occ fulltextsearch:live`

```
Memory: 12 MB
┌─ Indexing  ────
│ Provider:                      Account: 
│ Action: waiting
│ Document: 
│ Info: 
│ Title: 
│ Content size: 
│ Result: ok
└──
┌─ Status ────
│ Progress:       /   
│ Error:     14/14
│ Exception: Elasticsearch\Common\Exceptions\ServerErrorResponseException
│ Message: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [content] not present as part of path [attachment.content]
│ 
│ Index: files:3696

```

## Elastic log

```
[2018-08-25T10:19:33,890][DEBUG][o.e.a.b.TransportBulkAction] [OIcOFZU] failed to execute pipeline [attachment] for document [nc_fulltextsearch/standard/files:3696]
org.elasticsearch.ElasticsearchException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [content] not present as part of path [attachment.content]
	at org.elasticsearch.ingest.CompoundProcessor.newCompoundProcessorException(CompoundProcessor.java:156) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:107) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:58) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.PipelineExecutionService.innerExecute(PipelineExecutionService.java:155) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.PipelineExecutionService.access$100(PipelineExecutionService.java:43) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.PipelineExecutionService$1.doRun(PipelineExecutionService.java:78) [elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0.jar:6.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [content] not present as part of path [attachment.content]
	... 11 more
Caused by: java.lang.IllegalArgumentException: field [content] not present as part of path [attachment.content]
	at org.elasticsearch.ingest.IngestDocument.resolve(IngestDocument.java:344) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:112) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:129) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.common.ConvertProcessor.execute(ConvertProcessor.java:169) ~[?:?]
	at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:100) ~[elasticsearch-6.4.0.jar:6.4.0]
	... 9 more
[2018-08-25T10:19:33,914][WARN ][r.suppressed             ] path: /nc_fulltextsearch/standard/files%3A3696, params: {pipeline=attachment, index=nc_fulltextsearch, id=files:3696, type=standard}
org.elasticsearch.ElasticsearchException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [content] not present as part of path [attachment.content]
	at org.elasticsearch.ingest.CompoundProcessor.newCompoundProcessorException(CompoundProcessor.java:156) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:107) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:58) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.PipelineExecutionService.innerExecute(PipelineExecutionService.java:155) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.PipelineExecutionService.access$100(PipelineExecutionService.java:43) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.PipelineExecutionService$1.doRun(PipelineExecutionService.java:78) [elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0.jar:6.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [content] not present as part of path [attachment.content]
	... 11 more
Caused by: java.lang.IllegalArgumentException: field [content] not present as part of path [attachment.content]
	at org.elasticsearch.ingest.IngestDocument.resolve(IngestDocument.java:344) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:112) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:129) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.ingest.common.ConvertProcessor.execute(ConvertProcessor.java:169) ~[?:?]
	at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:100) ~[elasticsearch-6.4.0.jar:6.4.0]
	... 9 more
```

## Document

```
{
    "document": {
        "id": "3696",
        "providerId": "files",
        "access": {
            "ownerId": "xxx",
            "viewerId": null,
            "users": [],
            "groups": [],
            "circles": [],
            "links": []
        },
        "modifiedTime": 0,
        "title": "docs\/Wiss._MA_intern 8.pdf",
        "link": "",
        "index": null,
        "source": "files_local",
        "info": [],
        "hash": "53763cc9948ccc94ec94fbacfe8984be",
        "contentSize": 0,
        "tags": [
            "files_local"
        ],
        "more": [],
        "excerpts": [],
        "score": null
    },
    "content": ""
}
```

**Comment by morph027** [comment]
I have 13 documents showing this error, right now i see one obvious thing they all have in common: **They include a whitespace in the name**

**Comment by schliflo** [comment]
Probably related to this: https://github.com/nextcloud/fulltextsearch/issues/365

**Comment by morph027** [comment]
Thanks, looks so...

**Comment by daita** [comment]
fixed in RC2
