### ISSUE TITLE
Is the slash(and special char like star,commercial and ) allow in the Search field?

### ISSUE THREAD

**Issue by NicolasFr5** [nextcloud/fulltextsearch_elasticsearch#88]
Hi,

When I try to look for a date with slash like MM/YYYY, I got the error below on ES 6.8.5 .

Are the specials char like slash allowed?

2019-12-04T23:13:13,320][DEBUG][o.e.a.s.TransportSearchAction] [N2iYvWJ] [index_1][3], node[N2iYvWJUQWuvvGMaNbT0Zg], [P], s[STARTED], a[id=a6ZNPcx-Q12DGyQcSKShmg]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[index_1], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[standard], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, source={"from":0,"size":20,"query":{"bool":{"must":[{"bool":{"should":[{"bool":{"should":[{"bool":{"should":[{"match_phrase_prefix":{"content":{"query":"10/2019","slop":0,"max_expansions":50,"boost":1.0}}},{"match_phrase_prefix":{"title":{"query":"10/2019","slop":0,"max_expansions":50,"boost":1.0}}},{"match_phrase_prefix":{"share_names.XXXXX":{"query":"10/2019","slop":0,"max_expansions":50,"boost":1.0}}},{"wildcard":{"title":{"wildcard":"*10/2019*","boost":1.0}}},{"wildcard":{"share_names.XXXXX":{"wildcard":"*10/2019*","boost":1.0}}},{"query_string":{"query":"10/2019","fields":["parts.comments^1.0","parts.ocr^1.0"],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"filter":[{"bool":{"must":[{"term":{"provider":{"value":"files","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},{"bool":{"should":[{"term":{"owner":{"value":"XXXXX","boost":1.0}}},{"term":{"users":{"value":"XXXXX","boost":1.0}}},{"term":{"users":{"value":"__all","boost":1.0}}},{"term":{"groups":{"value":"admin","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},{"match_all":{"boost":1.0}},{"match_all":{"boost":1.0}},{"match_all":{"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"highlight":{"pre_tags":[""],"post_tags":[""],"fields":{"content":{},"parts.comments":{},"parts.ocr":{}}}}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [N2iYvWJ][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: Failed to parse query [10/2019]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1051) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:383) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:319) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:331) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:318) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:791) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:637) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:596) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:387) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.access$100(SearchService.java:126) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1107) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.5.jar:6.8.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse '10/2019': Lexical error at line 1, column 8.  Encountered: <EOF> after : "/2019"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:803) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1049) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:383) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:319) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:331) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:318) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:791) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:637) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:596) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:387) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.access$100(SearchService.java:126) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1107) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.5.jar:6.8.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 8.  Encountered: <EOF> after : "/2019"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1119) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.apache.lucene.queryparser.classic.QueryParser.getToken(QueryParser.java:854) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_3(QueryParser.java:668) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3_1(QueryParser.java:702) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.apache.lucene.queryparser.classic.QueryParser.jj_2_1(QueryParser.java:646) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:225) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:803) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1049) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:383) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:319) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:331) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:318) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:791) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:637) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:596) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:387) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.access$100(SearchService.java:126) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1107) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.5.jar:6.8.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]
[2019-12-04T23:13:13,320][DEBUG][o.e.a.s.TransportSearchAction] [N2iYvWJ] [index_1][0], node[N2iYvWJUQWuvvGMaNbT0Zg], [P], s[STARTED], a[id=3JCTmvKQR_eD3SWHOnyjWQ]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[index_1], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[standard], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, source={"from":0,"size":20,"query":{"bool":{"must":[{"bool":{"should":[{"bool":{"should":[{"bool":{"should":[{"match_phrase_prefix":{"content":{"query":"10/2019","slop":0,"max_expansions":50,"boost":1.0}}},{"match_phrase_prefix":{"title":{"query":"10/2019","slop":0,"max_expansions":50,"boost":1.0}}},{"match_phrase_prefix":{"share_names.XXXXX":{"query":"10/2019","slop":0,"max_expansions":50,"boost":1.0}}},{"wildcard":{"title":{"wildcard":"*10/2019*","boost":1.0}}},{"wildcard":{"share_names.XXXXX":{"wildcard":"*10/2019*","boost":1.0}}},{"query_string":{"query":"10/2019","fields":["parts.comments^1.0","parts.ocr^1.0"],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"filter":[{"bool":{"must":[{"term":{"provider":{"value":"files","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},{"bool":{"should":[{"term":{"owner":{"value":"XXXXX","boost":1.0}}},{"term":{"users":{"value":"XXXXX","boost":1.0}}},{"term":{"users":{"value":"__all","boost":1.0}}},{"term":{"groups":{"value":"admin","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},{"match_all":{"boost":1.0}},{"match_all":{"boost":1.0}},{"match_all":{"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"highlight":{"pre_tags":[""],"post_tags":[""],"fields":{"content":{},"parts.comments":{},"parts.ocr":{}}}}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [N2iYvWJ][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: Failed to parse query [10/2019]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1051) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:383) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:319) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:331) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:318) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:791) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:637) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:596) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:387) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.access$100(SearchService.java:126) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1107) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.5.jar:6.8.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse '10/2019': Lexical error at line 1, column 8.  Encountered: <EOF> after : "/2019"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114) ~[lucene-queryparser-7.7.2.jar:7.7.2 d4c30fc2856154f2c1fefc589eb7cd070a415b94 - janhoy - 2019-05-28 23:31:39]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:803) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1049) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:385) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:415) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:383) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:105) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:319) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:331) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:318) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:791) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:637) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:596) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:387) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService.access$100(SearchService.java:126) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359) ~[elasticsearch-6.8.5.jar:6.8.5]

**Comment by NicolasFr5** [comment]
Hi,

Just a simple msg to show some interest from my side ;) Is someone has also this issue ?
Thank in advance

Kr

**Comment by NicolasFr5** [comment]
Hi,

I got it how to escape special char... = 08"\""2019 in the nextcloud field search.
